import React from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

export default function ReviewResult({ review }) {
  if (!review) return null;

  return (
    <div className="relative w-full mt-8 bg-linear-to-br from-slate-800 via-gray-800 to-slate-900 p-8 rounded-3xl border border-gray-700/50 shadow-2xl backdrop-blur-sm">
      {/* Glass effect overlay */}
      <div className="absolute inset-0 bg-linear-to-br from-white/5 to-transparent rounded-3xl pointer-events-none"></div>
      
      {/* Animated gradient border */}
      <div className="absolute inset-0 rounded-3xl bg-linear-to-r from-indigo-500/20 via-purple-500/20 to-indigo-500/20 opacity-50 blur-sm animate-pulse"></div>
      
      {/* Content */}
      <div className="relative z-10">
        {/* Header */}
        <div className="flex items-center gap-3 mb-6 pb-4 border-b border-gray-700/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-linear-to-r from-indigo-500 to-purple-500 rounded-xl flex items-center justify-center shadow-lg">
              <span className="text-xl">🧠</span>
            </div>
            <div>
              <h2 className="text-xl font-bold bg-clip-text text-transparent bg-linear-to-r from-indigo-400 to-purple-400">
                AI Code Review
              </h2>
              <p className="text-xs text-gray-400 font-medium">Generated by CodeInsight AI</p>
            </div>
          </div>
          <div className="flex-1 h-px bg-linear-to-r from-indigo-500/50 via-purple-500/50 to-transparent ml-4"></div>
        </div>

        {/* Review content */}
        <div className="bg-gray-950/60 backdrop-blur-sm rounded-2xl p-6 border border-gray-700/30 shadow-inner">
          <div className="prose prose-sm prose-invert max-w-none text-gray-200 leading-relaxed">
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{
                h1: ({children}) => <h1 className="text-xl font-bold text-indigo-300 mb-4 flex items-center gap-2"><span>📋</span>{children}</h1>,
                h2: ({children}) => <h2 className="text-lg font-semibold text-purple-300 mb-3 flex items-center gap-2"><span>🔍</span>{children}</h2>,
                h3: ({children}) => <h3 className="text-base font-medium text-blue-300 mb-2 flex items-center gap-2"><span>💡</span>{children}</h3>,
                ul: ({children}) => <ul className="list-none space-y-2 my-4">{children}</ul>,
                li: ({children}) => <li className="flex items-start gap-2 text-gray-300"><span className="text-indigo-400 mt-1">•</span><span>{children}</span></li>,
                p: ({children}) => <p className="text-gray-200 mb-3 leading-relaxed">{children}</p>,
                code: ({children}) => <code className="bg-gray-800/80 text-indigo-300 px-2 py-1 rounded text-sm font-mono border border-gray-700/50">{children}</code>,
                pre: ({children}) => <pre className="bg-gray-900/80 border border-gray-700/50 rounded-xl p-4 overflow-x-auto my-4 shadow-inner">{children}</pre>,
                blockquote: ({children}) => <blockquote className="border-l-4 border-indigo-500 pl-4 py-2 bg-indigo-500/5 rounded-r-lg my-4 text-gray-300">{children}</blockquote>
              }}
            >
              {review}
            </ReactMarkdown>
          </div>
        </div>

        {/* Footer indicator */}
        <div className="flex items-center justify-center mt-6 pt-4 border-t border-gray-700/30">
          <div className="flex items-center gap-2 text-xs text-gray-500">
            <div className="flex space-x-1">
              <div className="w-1 h-1 rounded-full bg-indigo-500/60 animate-pulse"></div>
              <div className="w-1 h-1 rounded-full bg-purple-500/60 animate-pulse" style={{animationDelay: '0.2s'}}></div>
              <div className="w-1 h-1 rounded-full bg-blue-500/60 animate-pulse" style={{animationDelay: '0.4s'}}></div>
            </div>
            <span>Analysis Complete</span>
          </div>
        </div>
      </div>
    </div>
  );
}
